Repository macinv/docker-luigid, pull requests merged in 2021-09, with the labels that each got.

#10 Upgrade luigi to 2.8.3
  .gitignore
  Dockerfile
  requirements.txt
Labels: release

#11 Release 2.8.11
  requirements.txt
Labels: release

#8 Upgrade Luigi to 3.0.3
  requirements.txt
Labels: release, upgrade

#12 Downgrade sqlalchemy to 1.3.16
  requirements.txt
Labels: bug

#13 Downgrade sqlalchemy to 1.3.16 (#12)
  requirements.txt
Labels: release
